In [1]:
!pip install numpy pandas

In [3]:
import numpy as np

numpy -- это библиотека для научных вычислений

Написана на (кроме Python) C, немножко Fortran. А что это значит? Значит, что супер-пупер быстрая :)

И еще немножко фич с описания на оф. сайте:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Классно то, что массивы типизированы! Про это на лекции еще поговорим.

Один из способов создать массив:

In [4]:
a = np.array([1, 2, 3], dtype=np.int16)
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [5]:
a

array([1, 2, 3], dtype=int16)

### Задание: создайте двумерный массив (заполните чем угодно) с np.float32

In [ ]:
# TODO
# your code hear

Есть классное индексирование:

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int16)
print(a)

[[1 2 3]
 [4 5 6]]


Тут, думаю, понятно:

In [7]:
a[0]

array([1, 2, 3], dtype=int16)

Тут тоже:

In [8]:
a[1, 0]

4

Можно делать слайсы по осям. Получим 2-ой столбец матрицы:

In [9]:
a[:, 1]

array([2, 5], dtype=int16)

### Задание: выведите
* 3-ий столбец
* все элементы, кроме последнего, из предпоследнего столбца
* (*) а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки массива `b`

Конечно же, без всяких `for`, используем слайсы.

In [10]:
# создадим массив и заполним его рандомными элементами
# numpy умеет такое из коробки, используем np.random
b = np.random.randint(low=0, high=100, size=(20, 10))

# TODO
# your code hear

### Задание "на погуглить": выведите все четные элементы массива `c` (используя слайсы (да, и так тут можно))

In [ ]:
c = np.random.randint(low=0, high=100, size=100)

In [ ]:
# TODO
# your code hear

Немного посмотрим на операции с `np.array`:

In [11]:
a = np.random.randint(low=0, high=100, size=(3, 4))
b = np.random.randint(low=0, high=100, size=(3, 4))
c = np.random.randint(low=0, high=100, size=4)
d = 42

print(f"a: {a}", end="\n\n")
print(f"b: {b}", end="\n\n")
print(f"c: {c}", end="\n\n")

a: [[ 1 65 34 31]
 [40 24 45 17]
 [69 20 71  5]]

b: [[60 73 17 93]
 [47 13 63 26]
 [58 93 64 19]]

c: [73 40 15 85]



In [12]:
a + b

array([[ 61, 138,  51, 124],
       [ 87,  37, 108,  43],
       [127, 113, 135,  24]])

In [13]:
a - b

array([[-59,  -8,  17, -62],
       [ -7,  11, -18,  -9],
       [ 11, -73,   7, -14]])

In [14]:
b.T

array([[60, 47, 58],
       [73, 13, 93],
       [17, 63, 64],
       [93, 26, 19]])

Какое это умножение?

In [15]:
a * b

array([[  60, 4745,  578, 2883],
       [1880,  312, 2835,  442],
       [4002, 1860, 4544,   95]])

А это?

In [16]:
a @ b.T

array([[ 8266,  3840,  8868],
       [ 6498,  5469,  7755],
       [ 7272,  8106, 10501]])

In [17]:
a / b

array([[0.01666667, 0.89041096, 2.        , 0.33333333],
       [0.85106383, 1.84615385, 0.71428571, 0.65384615],
       [1.18965517, 0.21505376, 1.109375  , 0.26315789]])

In [18]:
a = np.array([[5, 4], [7, 8]])
for_pow = np.array([2, 3])

a ** for_pow

array([[ 25,  64],
       [ 49, 512]], dtype=int32)

In [19]:
np.sqrt(b)

array([[7.74596669, 8.54400375, 4.12310563, 9.64365076],
       [6.8556546 , 3.60555128, 7.93725393, 5.09901951],
       [7.61577311, 9.64365076, 8.        , 4.35889894]])

In [20]:
np.sum(b)

626

In [21]:
np.min(a[0])

4

А эта штука называется broadcasting. Можно почитать [тут](http://cs231n.github.io/python-numpy-tutorial/#numpy-broadcasting), а вообще на лекции расскажем.

In [ ]:
a + c

In [ ]:
b - d

### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [ ]:
# TODO
# your code hear

# PANDAAAAAS

In [24]:
import pandas as pd

Pandas — программная библиотека на языке Python для обработки и анализа данных. Работа pandas с данными строится поверх библиотеки NumPy.

Мы сейчас рассмотрим следующее: 
    - посмотрим два объекта из библиотеки pandas: Series и DataFrame.
    - пощупаем что это вообще такое.

In [ ]:
Series - объект похожий на list в питоне, он упорядочен и туда можно положить что угодно)
Однако на деле объект Series больше похож на упорядоченный словарь OrderedDict, 
тк у Series помимо значений есть еще и индексы.

In [25]:
a = pd.Series(data=['амир', 'миша', 'илья', 'зарина', 'игорь'])

In [26]:
# в строковом представлении в столбце слева - индексы, справа - значения.
a

0      амир
1      миша
2      илья
3    зарина
4     игорь
dtype: object

In [ ]:
# мы можем создавать серии со своей индексацией

a = pd.Series(data=['амир', 'миша', 'илья', 'зарина', 'игорь'], 
              index=[101,102,103,104,105])

In [ ]:
# и обращаться по индексу

a[103]

In [ ]:
# внутри все хранится в виде np.array

a.values

In [ ]:
a.index

In [ ]:
# мы можем создать Series вот так:

a = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})

In [ ]:
a

In [ ]:
# мы можем на лету поменять индекс

a.index=[1,2,3,4]

In [ ]:
a

In [ ]:
# у Series есть поле name и его мы можем изменять

a.name='fofoofof'

In [ ]:
a

___________

DataFrame в простом случае это таблица. 

у нее есть строки и столбцы.

столбцами в DataFrame являются объекты Series.

у DataFrame есть индекс по строкам, который по умолчанию задается в числовом диапазоне начниая с 0.

Индексом по столбцам является название колонок.

In [ ]:
d = {'колонка_1': [1, 2, 3, 4, 5], 
     'колонка_2': ['амир', 'миша', 'илья', 'зарина', 'игорь'], 
     'колонка_возраст':['засекречено','засекречено','засекречено','засекречено','засекречено']}
df = pd.DataFrame(data=d)

In [ ]:
df

основные способы создать DataFrame внизу - но мы с вами еще об этом поговорим на лекци

![](https://pbpython.com/images/pandas-dataframe-shadow.png)

In [ ]:
# пандас умеет загружать данные из разных источников
# разберем это на лекции, а пока давайте поиграемся с большим датафреймом.
# ниже пример загрузки из .tsv файла. 

titanik_csv = pd.read_csv('titanic.tsv', sep='|', index_col=0)

# 1. посмотреть как выглядят данные

In [ ]:
# вывести первые n элементов (по умолчанию n=5)

titanik_csv.head()

In [ ]:
# вывести 10 последних элементов (по умолчанию 5)

titanik_csv.tail(n=10)

In [ ]:
# вывести 10 случайных элементов (по умолчанию 5)

titanik_csv.sample(n=10)

In [ ]:
# тк pandas сделан на основе numpy, то мы можем так же стандартно посмотреть размерность таблички через
# свойство shape

titanik_csv.shape

>  мы видим что у нас 1309 строк и 14 колонок

In [ ]:
# мы в силах посмотреть всю табличку целиком.

titanik_csv

вы конечно можете посмотреть почти всю табличку целиком, вас ограничивают настройки отображения табличек в пандасе.

> это поля 

> pd.options.display.max_columns - максимальное число колонок которое будет отрисовано

> pd.options.display.max_rows - максимальное число строк которое будет отрисовано

конечно же как программисты мы можем все это поменять.

In [ ]:
pd.options.display.max_columns = 5

In [ ]:
pd.options.display.max_rows = 20

In [ ]:
# стало хуже?

titanik_csv

In [ ]:
# поставим чтоб было удобнее
pd.options.display.max_columns = 20
pd.options.display.max_rows = 200 # рекомендую ставить большое значение только если у вас мощный комп)

# 2. начнем смотреть столбцы ближе.

Для того чтобы понять какой столбец (признак) что означает почитайте об этом в разделе Data
https://www.kaggle.com/c/titanic/data . 

Пока вы не запомните, может быть полезно выписать название всех столбцов и что они значат прямо в нотбук - сюда:

* Survived - 
* Pclass - 
* Name - 
* Sex - 
* Age - 
* SibSp - 
* Parch - 
* Ticket - 
* Fare - 
* Cabin - 
* Embarked -

несколько полезных методов которые помогут быстро посмотреть общие характеристики данных:

1. .describe() - Выведет количество, среднее, стандартное отклонение, квантили, минимум и максимум всех **числовых признаков** (столбцов)
2. .columns - это поле а не метод (в конце скобки не надо писать). Выведет название всех колонок.
3. .count() - выведет количесто **не пропущенных** значений в каждом столбце (not nan значений)
4. .nunique() - выведет количество уникальных значений в каждом столбце
5. .dtypes - это поле а не метод (в конце скобки не надо писать). Выведет тип переменной хранящейся в каждом столбце


In [ ]:
titanik_csv.describe()

In [ ]:
titanik_csv.count()

In [ ]:
titanik_csv.nunique()

In [ ]:
# там где строки пандас по умолчанию пишет object
# иногда полезно посмотреть что тут.

titanik_csv.dtypes

мы можем напрямую обращаться к столбцу, столбцам, строке и строкам.

https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html

In [ ]:
# самый простой способ обратиться к столбцу - это написать его название через точку
# давайте обратимся к полю sex
# нам вернется pd.Series - прямо вся колонка


titanik_csv.sex

In [ ]:
# еще можно обратиться через квадратные скобки
# эффект будет совершенно таким же

titanik_csv["sex"]

In [ ]:
# через values мы можем получить np.array который хранится в вернувшемся объекте pd.Series

titanik_csv.sex.values

In [ ]:
# силами pandas мы можем посмотреть различные значения содержащиеся в объекте pd.Series
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html
# обратите внимание на доп параметры этой функции

titanik_csv.sex.value_counts()

# ТУДУШЕЧКА

> Вопрос Кого больше мужчин или женщин?

> ответ:

> Вопрос - объект какого типа возвращается после вызова  функции value_counts() ?

> ответ:


в пандасе мы можем получить срез сразу по нескольким колонкам, тогда вернется новый DataFrame а не Series

In [ ]:
titanik_csv[ ['sex', 'age'] ]

Самый каноничный способ обращения к полям - через loc или iloc

loc - позволяет обратиться по названию индексов, 

iloc - по нумерованному значению (то есть обращаемся через цифры, начиная с нуля)

In [ ]:
titanik_csv.loc[:, 'sex']

чтобы в дальнейшем экономить место - будем смотреть только первые 5 записей

In [ ]:
titanik_csv.loc[:, 'sex'].head()

In [ ]:
titanik_csv.loc[:, ['sex', 'age']].head()

In [ ]:
titanik_csv.loc[[12,13,14,17,17], ['sex', 'age']].head()

In [ ]:
titanik_csv.iloc[[12,13,14,17,17], [3, 4]].head()

# 3. мы можем работать с полями и изменять их как хотим.

In [ ]:
titanik_csv.loc[0, 'name']

например, давайте выделим только первую часть имени.

как мы это делаем с одной строкой?

In [ ]:
titanik_csv.loc[0, 'name'].split(',')[0]

чтобы проделать этот финт со всеми строками - не нужно итерироваться в цикле.

достаточно применить некоторую функцию ко всем строкам через метод apply

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html

In [ ]:
titanik_csv['name'].head().apply(lambda x: x.split(',')[0])

на основе этого мы можем создать новую колонку.

In [ ]:
titanik_csv['only_name'] = titanik_csv['name'].apply(lambda x: x.split(',')[0])

In [ ]:
titanik_csv.head()

Отлично, мы немного пощупали, Pandas, и продолжим изучать его подробнее на лекции.