# `numpy`

In [1]:
import numpy as np

## Как создать массив в `numpy`?

In [2]:
#Создадим всякие массивчики
string_array = np.array(["строка", 5])
float_array = np.array([5., 5])
float_array_2 = np.array([6.])
int_array = np.array([5, 4])
two_dimarray = np.array([[5, 4], [4, 6]])
one_dimarray = np.array([[5, 4], [4]])

In [3]:
#К массивам можно обращаться по 2 индексам. Возможны срезу по нескольким осям
example_list = [[5, 4], [7, 8]]
example_list[:, 1]

TypeError: list indices must be integers or slices, not tuple

In [4]:
example_arr = np.array([[5, 4], [7, 8]])
example_arr[:, 1]

array([4, 8])

In [5]:
#Можно получить параметры массива: тип данных, форму, размерность вдоль оси
two_dimarray = np.array([[5, 4], [4, 6]])
print("Размерность вдоль первой оси: {}".format(len(two_dimarray)))
print("Размерность массива: {}".format(two_dimarray.shape))
print("Тип данных в массиве: {}".format(two_dimarray.dtype))

#Давайте пожмем наш int64 до int8 (преподложим, что знаем ограничение на размер чисел)
import sys
print("Размер исходного массива %d" % sys.getsizeof(two_dimarray))
two_dimarray = two_dimarray.astype(np.int8)
print("Размер массива после преобразования %d" % sys.getsizeof(two_dimarray))

Размерность вдоль первой оси: 2
Размерность массива: (2, 2)
Тип данных в массиве: int32
Размер исходного массива 128
Размер массива после преобразования 116


### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [4]:
a=np.zeros((2, 2)) # array of all zeroes

In [6]:
np.shape(a)

(2, 2)

In [ ]:
shape()

In [7]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [8]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [9]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[-3, -3, -7,  9, -6],
       [-5,  2, -1,  0, -8]])

## Индексирование и слайсы

In [10]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[68 70  3 62 98 95 73 15 75 89]
 [98 68 74 97  9 25 28  9 73 98]
 [16 29 78 76 63 81 20 18 11 91]
 [84 88 69 34 40 94 18  4 91 66]
 [92 91 93  9 95 36 48 73 31 87]]


In [11]:
a[0]

array([68, 70,  3, 62, 98, 95, 73, 15, 75, 89])

In [12]:
a[0, 1] # the same as a[0][1]

70

In [13]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([70, 68, 29, 88, 91])

In [14]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([75, 73, 11, 91])

In [15]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([92, 93, 95, 48, 31])

In [16]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([91,  9, 36, 73, 87])

In [17]:
a[a > 0]

array([68, 70,  3, 62, 98, 95, 73, 15, 75, 89, 98, 68, 74, 97,  9, 25, 28,
        9, 73, 98, 16, 29, 78, 76, 63, 81, 20, 18, 11, 91, 84, 88, 69, 34,
       40, 94, 18,  4, 91, 66, 92, 91, 93,  9, 95, 36, 48, 73, 31, 87])

In [18]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[68, 70,  3, 62, 98, 95, 73, 15, 75, 89],
       [92, 91, 93,  9, 95, 36, 48, 73, 31, 87]])

### Для присваивания тоже работает!

In [19]:
a

array([[68, 70,  3, 62, 98, 95, 73, 15, 75, 89],
       [98, 68, 74, 97,  9, 25, 28,  9, 73, 98],
       [16, 29, 78, 76, 63, 81, 20, 18, 11, 91],
       [84, 88, 69, 34, 40, 94, 18,  4, 91, 66],
       [92, 91, 93,  9, 95, 36, 48, 73, 31, 87]])

In [20]:
a[1:-1, :] = 1
a

array([[68, 70,  3, 62, 98, 95, 73, 15, 75, 89],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [92, 91, 93,  9, 95, 36, 48, 73, 31, 87]])

In [21]:
a[:, 1:3] = np.arange(2)
a

array([[68,  0,  1, 62, 98, 95, 73, 15, 75, 89],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [92,  0,  1,  9, 95, 36, 48, 73, 31, 87]])

In [31]:
def simple_matrix_generator(n):
    a=np.zeros(n,n)
    for i in range(n):
            a[i][i]=1.
    return a

In [32]:
b=simple_matrix_generator(2)

TypeError: data type not understood

In [28]:
assert np.array_equal(simple_matrix_generator(4), np.array([[1., 0., 0., 0.], [0., 1., 0., 0.], [0., 0., 1., 0.], [0., 0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(3), np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(2), np.array([[1., 0.], [0., 1.]]))

TypeError: data type not understood

## Операции с `np.array`

In [33]:
#Преобразование формы массива 
example = np.array([5, 4, 7, 8])
print(example)
print(example.reshape(2, 2))
print(example.reshape(2, 2).flatten())

[5 4 7 8]
[[5 4]
 [7 8]]
[5 4 7 8]


In [34]:
# Массивы можно по-разному объединять и добавлять элементы
example = np.array([5., 6.])
example = np.append(example, example)
print(example)
example = np.array([[5.], [6.]])
print(np.concatenate((example, example), axis=0))
print(np.concatenate((example, example), axis=1))
print(np.vstack((example, example)))
print(np.hstack((example, example)))

[5. 6. 5. 6.]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]


In [35]:
#Над массивами numpy можно производить простейшие математические операции
example = np.array([5, 4, 7, 8])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Multidemensional")
example = np.array([[5, 4], [7, 8]])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Lessdimensional")
example = np.array([[5, 4], [7, 8]])
sep_arr = np.array([2, 3])
print(example / sep_arr)
print(example * sep_arr)
print(example + sep_arr)
print(example - sep_arr)
print(example ** sep_arr)

[2.5 2.  3.5 4. ]
[15 12 21 24]
[37 36 39 40]
[4 3 6 7]
[25 16 49 64]
Multidemensional
[[2.5 2. ]
 [3.5 4. ]]
[[15 12]
 [21 24]]
[[37 36]
 [39 40]]
[[4 3]
 [6 7]]
[[25 16]
 [49 64]]
Lessdimensional
[[2.5        1.33333333]
 [3.5        2.66666667]]
[[10 12]
 [14 24]]
[[ 7  7]
 [ 9 11]]
[[3 1]
 [5 5]]
[[ 25  64]
 [ 49 512]]


In [36]:
#Можно производить стандартные операции над векторами n-мерного пространства
example = np.array([[5, 4], [7, 8]])
print(example.transpose())

[[5 7]
 [4 8]]


In [39]:
#И снова калькулятор
def calculate(a, b=None, func="+"):
    #TODO Ну мы такое уже писали, кажется, совсем просто
    if func == "+":
        return a+b
    if func == "-":
        return a-b
    if func == "**":
        return a**b
    if func == "*":
        return a*b
    if func == "/":
        return a/b
    if func == "T":
        return a.T
    if func == "increment":
        #TODO увеличвает на 1 ДИАГОНАЛЬНЫЕ элементы, если матрица квадратная, иначе возвращает исходную матрицу
        if (np.shape(a)[0]==np.shape(a)[1]):
            for i in range (np.shape(a)[0]):
                a[i,i]+=1
        else:
            return a
    #Примените func ко всем эементам a

In [41]:
print(calculate(example, sample_vec, "**"))

[[         1         16      59049]
 [        16        625   60466176]
 [        49       4096 -808182895]]


In [38]:
example = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sample_vec = np.array([2, 4, 10])

assert np.array_equal(calculate(example, sample_vec, "/"), np.array([[ 0.5 ,  0.5 ,  0.3 ], [ 2.  ,  1.25,  0.6 ], [ 3.5 ,  2.  ,  0.9 ]]))
assert np.array_equal(calculate(example, 20, "/"), np.array([[ 0.05,  0.1 ,  0.15],
                                                             [ 0.2 ,  0.25,  0.3 ],
                                                             [ 0.35,  0.4 ,  0.45]]))
assert np.array_equal(calculate(example, 20, "+"), np.array([[21, 22, 23],
                                                             [24, 25, 26],
                                                             [27, 28, 29]]))
assert np.array_equal(calculate(example, sample_vec, "+"), np.array([[ 3,  6, 13],
                                                                     [ 6,  9, 16],
                                                                     [ 9, 12, 19]]))
assert np.array_equal(calculate(example, 20, "*"), np.array([[ 20,  40,  60],
                                                             [ 80, 100, 120],
                                                             [140, 160, 180]]))
assert np.array_equal(calculate(example, sample_vec, "*"), np.array([[ 2,  8, 30],
                                                                     [ 8, 20, 60],
                                                                     [14, 32, 90]]))
assert np.array_equal(calculate(example, 20, "-"), np.array([[-19, -18, -17],
                                                             [-16, -15, -14],
                                                             [-13, -12, -11]]))
assert np.array_equal(calculate(example, sample_vec, "-"), np.array([[-1, -2, -7],
                                                                     [ 2,  1, -4],
                                                                     [ 5,  4, -1]]))
assert np.array_equal(calculate(example, func="T"), np.array([[1, 4, 7],
                                                              [2, 5, 8],
                                                              [3, 6, 9]]))
assert np.array_equal(calculate(example, sample_vec, "**"), np.array([[         1,         16,      59049],
                                                                [        16,        625,   60466176],
                                                                [        49,       4096, 3486784401]]))

#!!!ALARM почему отрицательное число?
assert np.array_equal(calculate(example, 20, "**"), np.array([[                   1,              1048576,           3486784401],
                                                              [       1099511627776,       95367431640625,     3656158440062976],
                                                              [   79792266297612000,  1152921504606846976, -9223372036854775808]]))

assert np.array_equal(calculate(example, func="increment"), np.array([[  2.,   2.,   3.],
                                                                     [  4.,   6.,   6.],
                                                                     [  7.,   8.,  10.]]))
assert np.array_equal(calculate(sample_vec, func="increment"), sample_vec)

AssertionError: 

In [42]:
#Можно считать различные статистикиЮ суммы и другие значения по выбранной оси
example = np.array([[5, 4], [7, 8]])
print(example.sum())
print(example.sum(axis=0))
print(example.sum(axis=1))

#TODO Найти минимум по столбцам, максимум по строкам, среднее значение всей матриц, дисперсию по строкам и аргминимум по строке

24
[12 12]
[ 9 15]


### Волшебный `np.vectorize`

In [43]:
pow_2 = lambda x: x ** 2

In [44]:
pow_2(np.array([2, 3, 4]))

array([ 4,  9, 16], dtype=int32)

In [45]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [46]:
pow_2_vec = np.vectorize(pow_2)
pow_2_vec([2, 3, 4])

array([ 4,  9, 16])

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [ ]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())

### Задание: написать решалку линейных уравнений

In [ ]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...

def solution_finder(A, y):
    return None

### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [ ]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det

def cramer_solver(A, b):
    return None

## Few more things:

### `np.random.seed()`

In [47]:
for i in range(5):
    arr = np.arange(5)  # [0, 1, 2, 3, 4]
    np.random.seed(1)  # Reset random state
    np.random.shuffle(arr)  # Shuffle!
    print(arr)

[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]


In [48]:
np.random.seed(3)
print(np.random.random())

np.random.seed(3)
print(np.random.random())

0.5507979025745755
0.5507979025745755


### `np.isclose()`

In [49]:
np.float128(1 / 3) * 3 == 1

AttributeError: module 'numpy' has no attribute 'float128'

In [50]:
np.isclose(np.float128(1 / 3) * 3, 1)

AttributeError: module 'numpy' has no attribute 'float128'

In [ ]:
#Быстро сделали. Давайте сделаем решение методом Гаусса. Задание со звездочкой, я за 5 минут не смог написать

---