# `numpy`

In [3]:
import numpy as np

## Как создать массив в `numpy`?

In [4]:
#Создадим всякие массивчики
string_array = np.array(["строка", 5])
float_array = np.array([5., 5])
float_array_2 = np.array([6.])
int_array = np.array([5, 4])
two_dimarray = np.array([[5, 4], [4, 6]])
one_dimarray = np.array([[5, 4], [4]])

In [5]:
#К массивам можно обращаться по 2 индексам. Возможны срезу по нескольким осям
example_list = [[5, 4], [7, 8]]
example_list[:, 1]

TypeError: list indices must be integers or slices, not tuple

In [6]:
example_arr = np.array([[5, 4], [7, 8]])
example_arr[:, 1]

array([4, 8])

In [7]:
#Можно получить параметры массива: тип данных, форму, размерность вдоль оси
two_dimarray = np.array([[5, 4], [4, 6]])
print("Размерность вдоль первой оси: {}".format(len(two_dimarray)))
print("Размерность массива: {}".format(two_dimarray.shape))
print("Тип данных в массиве: {}".format(two_dimarray.dtype))

#Давайте пожмем наш int64 до int8 (преподложим, что знаем ограничение на размер чисел)
import sys
print("Размер исходного массива %d" % sys.getsizeof(two_dimarray))
two_dimarray = two_dimarray.astype(np.int8)
print("Размер массива после преобразования %d" % sys.getsizeof(two_dimarray))

Размерность вдоль первой оси: 2
Размерность массива: (2, 2)
Тип данных в массиве: int64
Размер исходного массива 144
Размер массива после преобразования 116


### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [8]:
np.zeros((2, 2)) # array of all zeroes

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [10]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [11]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[-9,  2,  8, -2, -9],
       [ 4,  3,  7, -8,  4]])

## Индексирование и слайсы

In [56]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[25 28 88 48 98 40 49  7 29 10]
 [40 80 43 97 37 31 72 65 71 77]
 [13 67 50  3 78 54 73 47 97 38]
 [29 28 50 20 26 28 64  9 42 47]
 [44 40 77 13  3 97 42 57 64 28]]


In [57]:
a[0]

array([25, 28, 88, 48, 98, 40, 49,  7, 29, 10])

In [58]:
a[0, 1] # the same as a[0][1]

28

In [59]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([28, 80, 67, 28, 40])

In [60]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([29, 71, 97, 42])

In [61]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([44, 77,  3, 42, 64])

In [62]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([40, 13, 97, 57, 28])

In [64]:
a[a > 0]

array([25, 28, 88, 48, 98, 40, 49,  7, 29, 10, 40, 80, 43, 97, 37, 31, 72,
       65, 71, 77, 13, 67, 50,  3, 78, 54, 73, 47, 97, 38, 29, 28, 50, 20,
       26, 28, 64,  9, 42, 47, 44, 40, 77, 13,  3, 97, 42, 57, 64, 28])

In [20]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[45, 42, 42, 78, 90, 64, 29, 43, 66,  2],
       [71, 85, 33, 57, 85, 51, 69, 64, 90, 22]])

### Для присваивания тоже работает!

In [69]:
a
for i in range(len(a)):
    a[i,i] = i
a

array([[ 0, 28, 88, 48, 98, 40, 49,  7, 29, 10],
       [40,  1, 43, 97, 37, 31, 72, 65, 71, 77],
       [13, 67,  2,  3, 78, 54, 73, 47, 97, 38],
       [29, 28, 50,  3, 26, 28, 64,  9, 42, 47],
       [44, 40, 77, 13,  4, 97, 42, 57, 64, 28]])

In [70]:
a[1:-1, :] = 1
a

array([[ 0, 28, 88, 48, 98, 40, 49,  7, 29, 10],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [44, 40, 77, 13,  4, 97, 42, 57, 64, 28]])

In [23]:
a[:, 1:3] = np.arange(2)
a

array([[45,  0,  1, 78, 90, 64, 29, 43, 66,  2],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [71,  0,  1, 57, 85, 51, 69, 64, 90, 22]])

In [54]:
def simple_matrix_generator(n):   
    return np.eye(n)


In [55]:
assert np.array_equal(simple_matrix_generator(4), np.array([[1., 0., 0., 0.], [0., 1., 0., 0.], [0., 0., 1., 0.], [0., 0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(3), np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(2), np.array([[1., 0.], [0., 1.]]))

## Операции с `np.array`

In [71]:
#Преобразование формы массива 
example = np.array([5, 4, 7, 8])
print(example)
print(example.reshape(2, 2))
print(example.reshape(2, 2).flatten())

[5 4 7 8]
[[5 4]
 [7 8]]
[5 4 7 8]


In [87]:
# Массивы можно по-разному объединять и добавлять элементы
example = np.array([5., 6.])
print(example.shape)
example = np.append(example, example)
print(example)
example = np.array([[5.], [6.]])
print(np.concatenate((example, example), axis=0),"axis=0")
print(np.concatenate((example, example), axis=1),"axis =1")
print(example)
print(np.vstack((example, example)))
print(np.hstack((example, example)))

(2,)
[5. 6. 5. 6.]
[[5.]
 [6.]
 [5.]
 [6.]] axis=0
[[5. 5.]
 [6. 6.]] axis =1
[[5.]
 [6.]]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]


In [79]:
#Над массивами numpy можно производить простейшие математические операции
example = np.array([5, 4, 7, 8])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Multidemensional")
example = np.array([[5, 4], [7, 8]])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Lessdimensional")
example = np.array([[5, 4], [7, 8]])
sep_arr = np.array([2, 3])
print(example / sep_arr)
print(example * sep_arr)
print(example + sep_arr)
print(example - sep_arr)
print(example ** sep_arr)

[2.5 2.  3.5 4. ]
[15 12 21 24]
[37 36 39 40]
[4 3 6 7]
[25 16 49 64]
Multidemensional
[[2.5 2. ]
 [3.5 4. ]]
[[15 12]
 [21 24]]
[[37 36]
 [39 40]]
[[4 3]
 [6 7]]
[[25 16]
 [49 64]]
Lessdimensional
[[2.5        1.33333333]
 [3.5        2.66666667]]
[[10 12]
 [14 24]]
[[ 7  7]
 [ 9 11]]
[[3 1]
 [5 5]]
[[ 25  64]
 [ 49 512]]


In [ ]:
#Можно производить стандартные операции над векторами n-мерного пространства
example = np.array([[5, 4], [7, 8]])
print(example.transpose())

In [92]:
#И снова калькулятор
def calculate(a, b=None, func="+"):
    #TODO Ну мы такое уже писали, кажется, совсем просто
    if func == "+":
        return a + b
    if func == "-":
        return a - b
    if func == "**":
        return a ** b
    if func == "*":
        return a * b
    if func == "/":
        return a / b
    if func == "T":
        return a.T
    if func == "increment":
        #TODO увеличвает на 1 ДИАГОНАЛЬНЫЕ элементы, если матрица квадратная, иначе возвращает исходную матрицу
        if len(a.shape) == 2:
            if a.shape[0] != a.shape[1]:
                return
            a = a + np.eye(a.shape[0])
        return a
    #Примените func ко всем эементам a
    return func(a)

In [93]:
example = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sample_vec = np.array([2, 4, 10])

assert np.array_equal(calculate(example, sample_vec, "/"), np.array([[ 0.5 ,  0.5 ,  0.3 ], [ 2.  ,  1.25,  0.6 ], [ 3.5 ,  2.  ,  0.9 ]]))
assert np.array_equal(calculate(example, 20, "/"), np.array([[ 0.05,  0.1 ,  0.15],
                                                             [ 0.2 ,  0.25,  0.3 ],
                                                             [ 0.35,  0.4 ,  0.45]]))
assert np.array_equal(calculate(example, 20, "+"), np.array([[21, 22, 23],
                                                             [24, 25, 26],
                                                             [27, 28, 29]]))
assert np.array_equal(calculate(example, sample_vec, "+"), np.array([[ 3,  6, 13],
                                                                     [ 6,  9, 16],
                                                                     [ 9, 12, 19]]))
assert np.array_equal(calculate(example, 20, "*"), np.array([[ 20,  40,  60],
                                                             [ 80, 100, 120],
                                                             [140, 160, 180]]))
assert np.array_equal(calculate(example, sample_vec, "*"), np.array([[ 2,  8, 30],
                                                                     [ 8, 20, 60],
                                                                     [14, 32, 90]]))
assert np.array_equal(calculate(example, 20, "-"), np.array([[-19, -18, -17],
                                                             [-16, -15, -14],
                                                             [-13, -12, -11]]))
assert np.array_equal(calculate(example, sample_vec, "-"), np.array([[-1, -2, -7],
                                                                     [ 2,  1, -4],
                                                                     [ 5,  4, -1]]))
assert np.array_equal(calculate(example, func="T"), np.array([[1, 4, 7],
                                                              [2, 5, 8],
                                                              [3, 6, 9]]))
assert np.array_equal(calculate(example, sample_vec, "**"), np.array([[         1,         16,      59049],
                                                                [        16,        625,   60466176],
                                                                [        49,       4096, 3486784401]]))

#!!!ALARM почему отрицательное число?
# assert np.array_equal(calculate(example, 20, "**"), np.array([[                   1,              1048576,           3486784401],
#                                                              [1099511627776,       95367431640625,     3656158440062976],
#                                                              [79792266297612000,  1152921504606846976, -9223372036854775808]]))

assert np.array_equal(calculate(example, func="increment"), np.array([[  2.,   2.,   3.],
                                                                     [  4.,   6.,   6.],
                                                                     [  7.,   8.,  10.]]))
assert np.array_equal(calculate(sample_vec, func="increment"), sample_vec)

In [ ]:
#Можно считать различные статистикиЮ суммы и другие значения по выбранной оси
example = np.array([[5, 4], [7, 8]])
print(example.sum())
print(example.sum(axis=0))
print(example.sum(axis=1))

#TODO Найти минимум по столбцам, максимум по строкам, среднее значение всей матриц, дисперсию по строкам и аргминимум по строке

### Волшебный `np.vectorize`

In [94]:
pow_2 = lambda x: x ** 2

In [101]:
%time
a = np.arange(100000)
pow_2(a)

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 10 µs


array([         0,          1,          4, ..., 9999400009, 9999600004,
       9999800001])

In [102]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [103]:
%time
pow_2_vec = np.vectorize(pow_2)
a = range(100000)
pow_2_vec(a)

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 10 µs


array([         0,          1,          4, ..., 9999400009, 9999600004,
       9999800001])

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [107]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)])
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())

[1487401  216099  791119 1416463  807843 1509519]
1509519


### Задание: написать решалку линейных уравнений

In [ ]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...
# np.linalg(A,y)

def solution_finder(A, y):
    ATA = A.T.dot(A)
    ATAI = ATA.I
    ATAIT = ATAI.dot(A.T)
    x = ATAIT.dot(y)
    x2 = np.linalg.solve(A,y)
    return x == x2

### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [ ]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det

def cramer_solver(A, b):
    return None

## Few more things:

### `np.random.seed()`

In [114]:
for i in range(5):
    arr = np.arange(5)  # [0, 1, 2, 3, 4]
    # np.random.seed(4)  # Reset random state
    np.random.shuffle(arr)  # Shuffle!
    print(arr)

[4 2 0 3 1]
[4 2 3 1 0]
[0 4 1 3 2]
[3 0 4 1 2]
[3 2 1 0 4]


In [115]:
np.random.seed(3)
print(np.random.random())

np.random.seed(3)
print(np.random.random())

0.5507979025745755
0.5507979025745755


### `np.isclose()`

In [ ]:
np.float128(1 / 3) * 3 == 1

In [ ]:
np.isclose(np.float128(1 / 3) * 3, 1)

In [ ]:
#Быстро сделали. Давайте сделаем решение методом Гаусса. Задание со звездочкой, я за 5 минут не смог написать

---