# `numpy`

In [1]:
import numpy as np

## Как создать массив в `numpy`?

In [2]:
#Создадим всякие массивчики
string_array = np.array(["строка", 5])
float_array = np.array([5., 5])
float_array_2 = np.array([6.])
int_array = np.array([5, 4])
two_dimarray = np.array([[5, 4], [4, 6]])
one_dimarray = np.array([[5, 4], [4]])

In [3]:
#К массивам можно обращаться по 2 индексам. Возможны срезу по нескольким осям
example_list = [[5, 4], [7, 8]]
example_list[:, 1]

TypeError: list indices must be integers or slices, not tuple

In [4]:
example_arr = np.array([[5, 4], [7, 8]])
example_arr[:, 1]

array([4, 8])

In [5]:
#Можно получить параметры массива: тип данных, форму, размерность вдоль оси
two_dimarray = np.array([[5, 4], [4, 6]])
print("Размерность вдоль первой оси: {}".format(len(two_dimarray)))
print("Размерность массива: {}".format(two_dimarray.shape))
print("Тип данных в массиве: {}".format(two_dimarray.dtype))

#Давайте пожмем наш int64 до int8 (преподложим, что знаем ограничение на размер чисел)
import sys
print("Размер исходного массива %d" % sys.getsizeof(two_dimarray))
two_dimarray = two_dimarray.astype(np.int8)
print("Размер массива после преобразования %d" % sys.getsizeof(two_dimarray))

Размерность вдоль первой оси: 2
Размерность массива: (2, 2)
Тип данных в массиве: int32
Размер исходного массива 128
Размер массива после преобразования 116


### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [6]:
np.zeros((2, 2)) # array of all zeroes

array([[0., 0.],
       [0., 0.]])

In [7]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [8]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [9]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[ -4,   0, -10,  -7,   7],
       [ -6,  -2,  -4,   5,  -7]])

## Индексирование и слайсы

In [10]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[17 61 37 16 97 56 18  2 38 91]
 [86 90 75 41 16  1 59 28 14 35]
 [52 44 68 75 24 87 37 73 88 20]
 [16  4 27 77  5 87 49 98 41 83]
 [63 81 60 11 56 15 87  5 85 30]]


In [11]:
a[0]

array([17, 61, 37, 16, 97, 56, 18,  2, 38, 91])

In [12]:
a[0, 1] # the same as a[0][1]

61

In [13]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([61, 90, 44,  4, 81])

In [14]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([38, 14, 88, 41])

In [15]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([63, 60, 56, 87, 85])

In [16]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([81, 11, 15,  5, 30])

In [28]:
a > 0

array([[ True, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [29]:
a[a > 0]

array([17,  1, 16, 97, 56, 18,  2, 38, 91,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, 63,  1, 11, 56, 15, 87,  5, 85, 30])

In [18]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[17, 61, 37, 16, 97, 56, 18,  2, 38, 91],
       [63, 81, 60, 11, 56, 15, 87,  5, 85, 30]])

### Для присваивания тоже работает!

In [19]:
a

array([[17, 61, 37, 16, 97, 56, 18,  2, 38, 91],
       [86, 90, 75, 41, 16,  1, 59, 28, 14, 35],
       [52, 44, 68, 75, 24, 87, 37, 73, 88, 20],
       [16,  4, 27, 77,  5, 87, 49, 98, 41, 83],
       [63, 81, 60, 11, 56, 15, 87,  5, 85, 30]])

In [34]:
a[0][0] = 0
a[1, 1] = 1
for i in range(min(a.shape)):
    a[i, i] = i
    
a

array([[ 0,  0,  1, 16, 97, 56, 18,  2, 38, 91],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  2,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  3,  1,  1,  1,  1,  1,  1],
       [63,  0,  1, 11,  4, 15, 87,  5, 85, 30]])

In [35]:
a[1:-1, :] = 1
a

array([[ 0,  0,  1, 16, 97, 56, 18,  2, 38, 91],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [63,  0,  1, 11,  4, 15, 87,  5, 85, 30]])

In [36]:
a[:, 1:3] = np.arange(2)
a

array([[ 0,  0,  1, 16, 97, 56, 18,  2, 38, 91],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [63,  0,  1, 11,  4, 15, 87,  5, 85, 30]])

In [26]:
def simple_matrix_generator(n):
    #TODO создать единичную матрицу размера n x n в виде numpy arra
    return np.eye(n)
#a = np.zeros((n, n))
#for i in range(n):
#   a[i, i] = 1



In [27]:
assert np.array_equal(simple_matrix_generator(4), np.array([[1., 0., 0., 0.], [0., 1., 0., 0.], [0., 0., 1., 0.], [0., 0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(3), np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(2), np.array([[1., 0.], [0., 1.]]))

## Операции с `np.array`

In [39]:
#Преобразование формы массива 
example = np.array([5, 4, 7, 8])
print(example)
print(example.reshape(2, 2))
print(example.reshape(2, -1)) #if we don't know the number of cols
print(example.reshape(2, 3)) #err because there will be spaces


print(example.reshape(2, 2).flatten())

[1, 2] #shape = (2,)
[[1, 2]] #shape = (2, 1)

[5 4 7 8]
[[5 4]
 [7 8]]
[[5 4]
 [7 8]]
[5 4 7 8]


In [41]:
# Массивы можно по-разному объединять и добавлять элементы
example = np.array([5., 6.])
example = np.append(example, example)
print(example)
example = np.array([[5.], [6.]])
print(np.concatenate((example, example), axis=0))
print(np.concatenate((example, example), axis=1))
print(np.vstack((example, example)))
print(np.hstack((example, example)))

[5. 6. 5. 6.]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]


In [42]:
#Над массивами numpy можно производить простейшие математические операции
example = np.array([5, 4, 7, 8])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Multidemensional")
example = np.array([[5, 4], [7, 8]])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Lessdimensional")
example = np.array([[5, 4], [7, 8]])
sep_arr = np.array([2, 3])
print(example / sep_arr)
print(example * sep_arr)
print(example + sep_arr)
print(example - sep_arr)
print(example ** sep_arr)

[2.5 2.  3.5 4. ]
[15 12 21 24]
[37 36 39 40]
[4 3 6 7]
[25 16 49 64]
Multidemensional
[[2.5 2. ]
 [3.5 4. ]]
[[15 12]
 [21 24]]
[[37 36]
 [39 40]]
[[4 3]
 [6 7]]
[[25 16]
 [49 64]]
Lessdimensional
[[2.5        1.33333333]
 [3.5        2.66666667]]
[[10 12]
 [14 24]]
[[ 7  7]
 [ 9 11]]
[[3 1]
 [5 5]]
[[ 25  64]
 [ 49 512]]


In [43]:
#Можно производить стандартные операции над векторами n-мерного пространства
example = np.array([[5, 4], [7, 8]])
print(example.transpose())

[[5 7]
 [4 8]]


In [55]:
#И снова калькулятор
def calculate(a, b=None, func="+"):
    #TODO Ну мы такое уже писали, кажется, совсем просто
    if func == "+":
        return a + b
    if func == "-":
        return a - b
    if func == "**":
        return a ** b
    if func == "*":
        return a * b
    if func == "/":
        return a / b
    if func == "T":
        return a.transpose()
    if func == "increment":
        #TODO увеличвает на 1 ДИАГОНАЛЬНЫЕ элементы, если матрица квадратная, иначе возвращает исходную матрицу
        if a.shape[0] == a.shape[1]:
            return a + np.eye(a.shape[0])
        return a
    #Примените func ко всем эементам a
    return func(a)

In [58]:
example = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sample_vec = np.array([2, 4, 10])

assert np.array_equal(calculate(example, sample_vec, "/"), np.array([[ 0.5 ,  0.5 ,  0.3 ], [ 2.  ,  1.25,  0.6 ], [ 3.5 ,  2.  ,  0.9 ]]))
assert np.array_equal(calculate(example, 20, "/"), np.array([[ 0.05,  0.1 ,  0.15],
                                                             [ 0.2 ,  0.25,  0.3 ],
                                                             [ 0.35,  0.4 ,  0.45]]))
assert np.array_equal(calculate(example, 20, "+"), np.array([[21, 22, 23],
                                                             [24, 25, 26],
                                                             [27, 28, 29]]))
assert np.array_equal(calculate(example, sample_vec, "+"), np.array([[ 3,  6, 13],
                                                                     [ 6,  9, 16],
                                                                     [ 9, 12, 19]]))
assert np.array_equal(calculate(example, 20, "*"), np.array([[ 20,  40,  60],
                                                             [ 80, 100, 120],
                                                             [140, 160, 180]]))
assert np.array_equal(calculate(example, sample_vec, "*"), np.array([[ 2,  8, 30],
                                                                     [ 8, 20, 60],
                                                                     [14, 32, 90]]))
assert np.array_equal(calculate(example, 20, "-"), np.array([[-19, -18, -17],
                                                             [-16, -15, -14],
                                                             [-13, -12, -11]]))
assert np.array_equal(calculate(example, sample_vec, "-"), np.array([[-1, -2, -7],
                                                                     [ 2,  1, -4],
                                                                     [ 5,  4, -1]]))
assert np.array_equal(calculate(example, func="T"), np.array([[1, 4, 7],
                                                              [2, 5, 8],
                                                              [3, 6, 9]]))
assert np.array_equal(calculate(example, sample_vec, "**"), np.array([[         1,         16,      59049],
                                                                [        16,        625,   60466176],
                                                                [        49,       4096, 3486784401]]))

#!!!ALARM почему отрицательное число?
assert np.array_equal(calculate(example, 20, "**"), np.array([[                   1,              1048576,           3486784401],
                                                              [       1099511627776,       95367431640625,     3656158440062976],
                                                              [   79792266297612000,  1152921504606846976, -9223372036854775808]]))

assert np.array_equal(calculate(example, func="increment"), np.array([[  2.,   2.,   3.],
                                                                     [  4.,   6.,   6.],
                                                                     [  7.,   8.,  10.]]))
assert np.array_equal(calculate(sample_vec, func="increment"), sample_vec)

AssertionError: 

In [57]:
#Можно считать различные статистикиЮ суммы и другие значения по выбранной оси
example = np.array([[5, 4], [7, 8]])
print(example.sum())
print(example.sum(axis=0))
print(example.sum(axis=1))

#TODO Найти минимум по столбцам, максимум по строкам, среднее значение всей матриц, дисперсию по строкам и аргминимум по строке

24
[12 12]
[ 9 15]


### Волшебный `np.vectorize`

In [59]:
pow_2 = lambda x: x ** 2

In [60]:
pow_2(np.array([2, 3, 4]))

array([ 4,  9, 16], dtype=int32)

In [61]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [62]:
pow_2_vec = np.vectorize(pow_2)
pow_2_vec([2, 3, 4])

array([ 4,  9, 16])

In [63]:
a = np.array([1, 1])
b = np.array([2, 2])
a.dot(b)

4

In [64]:
a = np.array([[1, 1]])
b = np.array([[2], [2]])
b.dot(a)

array([[2, 2],
       [2, 2]])

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [65]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())

2152733


### Задание: написать решалку линейных уравнений

In [66]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...

def solution_finder(A, y):
    x = (A.transpose() * y) / (A.transpose() * A) 
    return x
#return np.linalg.inv(A.T @ A).dot(A.T).dot(y)

### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [ ]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det

def cramer_solver(A, b):
    det = np.linalg.det(A)
    ans = np.array(b.shape)
    for i in range(b.shape):
        ans[i] = np.linalg.det(A[])
    return None

# доп задача за балл, кидать в личку!!

## Few more things:

### `np.random.seed()`

In [67]:
for i in range(5):
    arr = np.arange(5)  # [0, 1, 2, 3, 4]
    np.random.seed(1)  # Reset random state
    np.random.shuffle(arr)  # Shuffle!
    print(arr)

[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]


In [68]:
np.random.seed(3)
print(np.random.random())

np.random.seed(3)
print(np.random.random())

0.5507979025745755
0.5507979025745755


### `np.isclose()`

In [ ]:
np.float128(1 / 3) * 3 == 1

In [ ]:
np.isclose(np.float128(1 / 3) * 3, 1)

In [ ]:
#Быстро сделали. Давайте сделаем решение методом Гаусса. Задание со звездочкой, я за 5 минут не смог написать

---